---
- :name: :user_defined_id
  :type: :string
  :label: Identifier
  :required: true
  :default_form_field: false
  :optional_form_field: false
  :order: 100
- :name: :name
  :type: :string
  :label: Name
  :required: true
  :default_form_field: true
  :optional_form_field: false
  :order: 1
- :name: :alternate_name
  :type: :string
  :label: Alternate Name
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 2
- :name: :creator
  :type: :string
  :label: Creator
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 3
- :name: :contributor
  :type: :string
  :label: Contributor
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 4
- :name: :description
  :type: :html
  :label: Description
  :default_form_field: true
  :optional_form_field: false
  :order: 5
- :name: :subject
  :type: :html
  :label: Subject
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 6
- :name: :transcription
  :type: :html
  :label: Transcription
  :default_form_field: false
  :optional_form_field: true
  :order: 7
- :name: :date_created
  :type: :date
  :label: Date Created
  :default_form_field: false
  :optional_form_field: true
  :order: 8
- :name: :date_published
  :type: :date
  :label: Date Published
  :default_form_field: false
  :optional_form_field: true
  :order: 9
- :name: :date_modified
  :type: :date
  :label: Date Modified
  :default_form_field: false
  :optional_form_field: true
  :order: 10
- :name: :original_language
  :type: :string
  :label: Original Language
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 11
- :name: :rights
  :type: :string
  :label: Rights
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 12
- :name: :call_number
  :type: :string
  :label: Call Number
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 13
- :name: :provenance
  :type: :string
  :label: Provenance
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 14
- :name: :publisher
  :type: :string
  :label: Publisher
  :multiple: true
  :default_form_field: false
  :optional_form_field: true
  :order: 15
- :name: :manuscript_url
  :type: :string
  :label: Digitized Manuscript
  :default_form_field: false
  :optional_form_field: true
  :order: 16
