---
:fields:
  - :name: :actors
    :active: true
    :type: :html
    :label: Actors
    :multiple: true
    :default_form_field: false
    :optional_form_field: true
    :order: 1
    :boost: 3
  - :name: :alternative_title
    :active: true
    :type: :string
    :label: Alternative Title
    :required: true
    :default_form_field: true
    :optional_form_field: false
    :order: 2
    :boost: 10
    :immutable: [name, active, type, required, default_form_field, optional_form_field, order]
  - :name: :authentic_texts
    :active: true
    :type: :string
    :label: Authentic Texts
    :multiple: true
    :default_form_field: false
    :optional_form_field: true
    :order: 3
    :placeholder: "Example: \"French\""
  - :name: :heading
    :active: true
    :type: :string
    :label: Heading
    :multiple: true
    :default_form_field: false
    :optional_form_field: true
    :order: 4
    :placeholder: "Example: \"French\""
  - :name: :document_text
    :active: true
    :type: :html
    :label: Document Text
    :default_form_field: false
    :optional_form_field: true
    :order: 5
  - :name: :type_of_document
    :active: true
    :type: :html
    :label: Type of Document
    :default_form_field: false
    :optional_form_field: true
    :order: 6
  - :name: :name
    :active: true
    :type: :string
    :label: Title
    :required: true
    :default_form_field: true
    :optional_form_field: false
    :order: 7
    :boost: 10
    :immutable: [name, active, type, required, default_form_field, optional_form_field, order]
  - :name: :order
    :active: true
    :type: :string
    :label: Order
    :multiple: false
    :default_form_field: false
    :optional_form_field: true
    :order: 8
  - :name: :parent_id
    :active: true
    :type: :string
    :label: Parent id
    :multiple: false
    :default_form_field: false
    :optional_form_field: true
    :order: 9
  - :name: :manuscript_url
    :active: true
    :type: :string
    :label: PDF Link
    :default_form_field: false
    :optional_form_field: true
    :order: 10
    :placeholder: "http://"
    :help: Link to externally hosted manuscript viewer.
  - :name: :document_symbol
    :active: true
    :type: :string
    :label: Document Symbol
    :default_form_field: false
    :optional_form_field: true
    :order: 11
    :placeholder: "A 123"
    :help: Document symbol
  - :name: :mtdsg_reference
    :active: true
    :type: :string
    :label: MTDSG Reference
    :default_form_field: false
    :optional_form_field: true
    :order: 12
    :placeholder: "V-1"
    :help: MTDSG Reference
  - :name: :registration_number
    :active: true
    :type: :string
    :label: Registration Number
    :default_form_field: false
    :optional_form_field: true
    :order: 13
  - :name: :source
    :active: true
    :type: :string
    :label: Source
    :default_form_field: false
    :optional_form_field: true
    :order: 14
  - :name: :conclusion
    :active: true
    :type: :date
    :label: Conclusion
    :default_form_field: false
    :optional_form_field: true
    :order: 15
  - :name: :place_of_conclusion
    :active: true
    :type: :string
    :label: Place of conclusion
    :default_form_field: false
    :optional_form_field: true
    :order: 16
  - :name: :entry_into_force
    :active: true
    :type: :string
    :label: Entry into force
    :default_form_field: false
    :optional_form_field: true
    :order: 17
  - :name: :registration
    :active: true
    :type: :date
    :label: Registration
    :default_form_field: false
    :optional_form_field: true
    :order: 18
  - :name: :coverage_spatial
    :active: true
    :type: :string
    :label: Coverage spatial
    :default_form_field: false
    :optional_form_field: true
    :order: 19
  - :name: :type
    :active: true
    :type: :string
    :label: Type
    :default_form_field: false
    :optional_form_field: true
    :order: 20
  - :name: :coverage_temporal
    :active: true
    :type: :string
    :label: Coverage temporal
    :default_form_field: false
    :optional_form_field: true
    :order: 21
  - :name: :document_group
    :active: true
    :type: :string
    :label: Document group
    :default_form_field: false
    :optional_form_field: true
    :order: 22
  - :name: :document_classification
    :active: true
    :type: :string
    :label: Document classification
    :default_form_field: false
    :optional_form_field: true
    :order: 23
  - :name: :ctc_url
    :active: true
    :type: :string
    :label: CTC url
    :default_form_field: false
    :optional_form_field: true
    :order: 24
  - :name: :participants
    :active: true
    :type: :string
    :label: Participants
    :default_form_field: false
    :optional_form_field: true
    :order: 25
  - :name: :promulgated_by
    :active: true
    :type: :string
    :label: Promulgated by
    :default_form_field: false
    :optional_form_field: true
    :order: 26
  - :name: :date_promulgated
    :active: true
    :type: :date
    :label: Date promulgated
    :default_form_field: false
    :optional_form_field: true
    :order: 27
  - :name: :place_promulgated
    :active: true
    :type: :string
    :label: Place promulgated
    :default_form_field: false
    :optional_form_field: true
    :order: 28
  - :name: :footnotes
    :active: true
    :type: :string
    :label: Footnotes
    :default_form_field: false
    :optional_form_field: true
    :order: 29
  - :name: :rights_holder
    :active: true
    :type: :string
    :label: Rights Holder
    :default_form_field: false
    :optional_form_field: true
    :order: 30
  - :name: :rights_holder_website
    :active: true
    :type: :string
    :label: Rights Holder Website
    :default_form_field: false
    :optional_form_field: true
    :order: 31
  - :name: :type_of_text
    :active: true
    :type: :string
    :label: Type of Text
    :default_form_field: false
    :optional_form_field: true
    :order: 32
:facets:
  - :name: :document_group
    :field_name: :document_group
    :label: Document Group
  - :name: :source
    :field_name: :source
    :label: Source
  - :name: :document_classification
    :field_name: :document_classification
    :label: Document Classification
:sorts:
  - :name: :name
    :field_name: :name
    :direction: :asc
    :label: Name
  - :name: :creator
    :field_name: :creator
    :direction: :asc
    :label: Creator
